baseURL = "/"
languageCode = "en-us"
title = "CANS 2025"
theme = "ananke"
enableRobotsTXT = false
minify = true
relativeURLs = true
canonifyURLs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
text_color = ""
background_color_class = "bg-gray"
background = ""
author = "CANS2025 Organizing Committee"
favicon = "favicon/favicon.ico"
site_logo = "/images/cans2025_logo.webp"
images = ["https://cy2sec.comm.eng.osaka-u.ac.jp/miyaji-lab/event/cans2025/images/og-image.webp"]
description = ""
show_author = false
show_reading_time = false
show_date = false

[taxonomies]
  tag = ""
  category = ""

[menu]

  # --- Home ---
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  # --- Submission ---
  [[menu.main]]
    identifier = "submission"
    name = "Submission"
    url = "#"
    weight = 5

    [[menu.main]]
      parent = "submission"
      identifier = "cfp"
      name = "Call for Papers"
      url = "/Call-for-Papers/"
      weight = 1

    [[menu.main]]
      parent = "submission"
      identifier = "cfposter"
      name = "Call for Poster"
      url = "/Call-for-Poster/"
      weight = 2
    
    [[menu.main]]
      parent = "submission"
      identifier = "submission"
      name = "submission"
      url = "/submission/"
      weight = 3

    [[menu.main]]
      parent = "submission"
      identifier = "important-date"
      name = "Important Date"
      url = "/Important-date/"
      weight = 4

    [[menu.main]]
      parent = "submission"
      identifier = "stipend"
      name = "Stipend"
      url = "/stipend/"
      weight = 5

  # --- Program ---
  [[menu.main]]
    identifier = "program"
    name = "Program"
    url = "#"
    weight = 10
    
  [[menu.main]]
    parent = "program"
    identifier = "Conference Program"
    name = "Conference Program"
    url = "/program/"
    weight = 1

    [[menu.main]]
      parent = "program"
      identifier = "accepted-papers"
      name = "Accepted Papers"
      url = "/accepted-papers/"
      weight = 2

    [[menu.main]]
      parent = "program"
      identifier = "invited-talk"
      name = "Invited Talk"
      url = "/invited_talk/"
      weight = 3

    [[menu.main]]
      parent = "program"
      identifier = "Poster Session"
      name = "Poster Session"
      url = "/posters/"
      weight = 4

    [[menu.main]]
      parent = "program"
      identifier = "Access maps"
      name = "Access maps"
      url = "/map/"
      weight = 5


  # --- Conference Info ---
  [[menu.main]]
    identifier = "conference-info"
    name = "Conference Info"
    url = "#"
    weight = 15

    

    [[menu.main]]
      parent = "conference-info"
      identifier = "visa"
      name = "Visa"
      url = "/visa/"
      weight = 2

    [[menu.main]]
      parent = "conference-info"
      identifier = "committee"
      name = "Committee"
      url = "/committee/"
      weight = 3

    [[menu.main]]
      parent = "conference-info"
      identifier = "venue"
      name = "Venue"
      url = "/venue/"
      weight = 5

    [[menu.main]]
      parent = "conference-info"
      identifier = "about-osaka"
      name = "About Osaka"
      url = "/about-osaka/"
      weight = 6

[[menu.main]]
  identifier = "registration"
  name = "Registration"
  url = "/registration/"
  weight = 20

[[menu.main]]
  identifier = "sponsorship"
  name = "Sponsorship"
  url = "/sponsorship/"
  weight = 25